apiVersion: config.openshift.io/v1alpha1
kind: UpdateStatus
metadata:
  name: cluster
spec: {}
status:
  controlPlane:
    assessment: Progressing
    completion: 0
    conditions:
    - lastTransitionTime: "2023-11-20T14:06:46Z"
      message: 'Working towards 4.15.0-ec.2: 357 of 1021 done (34% complete), waiting
      up to 40 minutes on cluster-api'
      reason: ClusterVersionProgressing
      status: "True"
      type: UpdateProgressing
    startedAt: "2023-11-20T14:06:46Z"
    versions:
      previous: 4.15.0-ec.1
      target: 4.15.0-ec.2
