apiVersion: config.openshift.io/v1alpha1
kind: UpdateStatus
metadata:
  name: cluster
spec: {}
status:
  controlPlane:
    assessment: Progressing
    completion: 0
    conditions:
    - lastTransitionTime: "2023-11-21T15:02:46Z"
      message: 'Working towards 4.15.0-ec.2: 106 of 863 done (12% complete), waiting
      on etcd, kube-apiserver'
      reason: ClusterVersionProgressing
      status: "True"
      type: UpdateProgressing
    startedAt: "2023-11-21T15:02:46Z"
    versions:
      previous: 4.14.1
      target: 4.15.0-ec.2
      previousPartial: true
