apiVersion: config.openshift.io/v1alpha1
kind: UpdateStatus
metadata:
  name: cluster
spec: {}
status:
  controlPlane:
    assessment: Progressing
    completion: 0
    conditions:
    - lastTransitionTime: "2024-02-27T15:42:58Z"
      message: 'Error while reconciling 4.16.0-ec.3: the cluster operator machine-config
        is degraded'
      reason: ClusterVersionProgressing
      status: "True"
      type: UpdateProgressing
    startedAt: "2024-02-27T12:12:27Z"
    versions:
      previous: 4.16.0-ec.2
      target: 4.16.0-ec.3
