apiVersion: config.openshift.io/v1alpha1
kind: UpdateStatus
metadata:
  name: cluster
spec: {}
status:
  controlPlane:

    informers:
    - name: ota-1268-prototype
      insights:
      - type: ClusterVersion
        cv:
          resource:
            apiGroup: config.openshift.io/v1
            kind: ClusterVersion
            name: version
          conditions:
          - lastTransitionTime: "2024-02-27T12:15:21Z"
            message: 'Working towards 4.17.0-ec.0: 110 of 892 done (12% complete), waiting on etcd, kube-apiserver'
            reason: ClusterOperatorsUpdating
            status: "True"
            type: Updating
          versions:
            previous: 4.16.0-0.nightly-2024-08-01-082745
            target: 4.17.0-ec.0
          startedAt: "2024-02-27T12:12:27Z"
          estimatedCompletedAt: "2024-02-27T13:24:21Z"
          assessment: Progressing
          completion: 6
      - type: ClusterOperator
        co:
          name: authentication
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:29:12Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:28:45Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: baremetal
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:14:45Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:14:45Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: cloud-controller-manager
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:12:45Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:12:45Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: cloud-credential
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:12:29Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:25:57Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: cluster-autoscaler
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:24:47Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:24:47Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: config-operator
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:14:15Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:14:15Z"
            reason: Updated
      - type: ClusterOperator
        co:
          name: console
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:29:16Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:34:58Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: control-plane-machine-set
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:14:45Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:14:45Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: csi-snapshot-controller
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:20:48Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:20:48Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: dns
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:15:10Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:14:45Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: etcd
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:16:19Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T16:00:26Z"
            reason: Updated
      - type: ClusterOperator
        co:
          name: image-registry
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:28:27Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:28:27Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: ingress
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:30:14Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:24:48Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: insights
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:20:45Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:20:45Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: kube-apiserver
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:22:32Z"
          - type: Updating
            status: "True"
            lastTransitionTime: "2024-08-05T15:58:26Z"
      - type: ClusterOperator
        co:
          name: kube-controller-manager
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:17:38Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:29:40Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: kube-scheduler
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:20:35Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:24:55Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: kube-storage-version-migrator
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:14:16Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:14:16Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: machine-api
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:24:45Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:24:45Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: machine-approver
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:14:45Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:14:45Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: machine-config
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:15:28Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:15:30Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: marketplace
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:15:07Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:15:07Z"
            reason: Pending
            version: 4.16.0-0.nightly-2024-08-01-082745
      - type: ClusterOperator
        co:
          name: monitoring
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:34:09Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:34:09Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: network
          conditions:
          - type: Healthy
            status: "False"
            reason: "Degraded"
            lastTransitionTime: "2024-08-05T16:00:26Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:20:35Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: node-tuning
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:14:46Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:14:46Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: openshift-apiserver
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T16:00:21Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:23:00Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: openshift-controller-manager
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:28:10Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:28:10Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: openshift-samples
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:28:36Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:28:36Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: operator-lifecycle-manager
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:15:12Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:15:12Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: operator-lifecycle-manager-catalog
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:15:12Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:15:42Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: operator-lifecycle-manager-packageserver
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:22:24Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:22:24Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: service-ca
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:14:16Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:14:18Z"
            reason: Pending
      - type: ClusterOperator
        co:
          name: storage
          conditions:
          - type: Healthy
            status: "True"
            lastTransitionTime: "2024-08-05T15:14:56Z"
          - type: Updating
            status: "False"
            lastTransitionTime: "2024-08-05T15:14:56Z"
            reason: Pending
        nodes:
          name: master
          kind: MachineConfigPool
          apiGroup: machineconfiguration.openshift.io/v1
          nodes:
          - name: ip-10-0-8-37.ec2.internal
            kind: Node
            version: 4.16.0-0.nightly-2024-08-01-082745
            conditions:
            - type: Updating
              status: "False"
              lastTransitionTime: "2024-08-05T15:14:45Z"
              reason: Pending
    conditions:
    - lastTransitionTime: "2024-02-27T12:15:21Z"
      message: 'Working towards 4.17.0-ec.0: 110 of 892 done (12% complete), waiting on etcd, kube-apiserver'
      reason: ClusterVersionProgressing
      status: "True"
      type: Updating
