apiVersion: v1
items:
  - apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    metadata:
      creationTimestamp: "2024-02-01T15:18:40Z"
      generation: 5
      labels:
        machineconfiguration.openshift.io/mco-built-in: ""
        operator.machineconfiguration.openshift.io/required-for-upgrade: ""
        pools.operator.machineconfiguration.openshift.io/master: ""
      name: master
      resourceVersion: "57342"
      uid: cf5b550e-d977-43af-87ab-70d621021f3a
    spec:
      configuration:
        name: rendered-master-9774a6215d3b1e57660c513ce0b5a630
        source:
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 00-master
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 01-master-container-runtime
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 01-master-kubelet
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 97-master-generated-kubelet
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 98-master-generated-kubelet
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 99-master-generated-registries
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 99-master-ssh
      machineConfigSelector:
        matchLabels:
          machineconfiguration.openshift.io/role: master
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/master: ""
      paused: false
    status:
      conditions:
        - lastTransitionTime: "2024-02-01T15:18:53Z"
          message: ""
          reason: ""
          status: "False"
          type: RenderDegraded
        - lastTransitionTime: "2024-02-01T15:21:50Z"
          message: ""
          reason: ""
          status: "False"
          type: NodeDegraded
        - lastTransitionTime: "2024-02-01T15:21:50Z"
          message: ""
          reason: ""
          status: "False"
          type: Degraded
        - lastTransitionTime: "2024-02-01T16:14:47Z"
          message: All nodes are updated with MachineConfig rendered-master-9774a6215d3b1e57660c513ce0b5a630
          reason: ""
          status: "True"
          type: Updated
        - lastTransitionTime: "2024-02-01T16:14:47Z"
          message: ""
          reason: ""
          status: "False"
          type: Updating
      configuration:
        name: rendered-master-9774a6215d3b1e57660c513ce0b5a630
      degradedMachineCount: 0
      machineCount: 3
      observedGeneration: 5
      readyMachineCount: 3
      unavailableMachineCount: 0
      updatedMachineCount: 3
  - apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    metadata:
      creationTimestamp: "2024-02-01T15:18:40Z"
      generation: 5
      labels:
        machineconfiguration.openshift.io/mco-built-in: ""
        pools.operator.machineconfiguration.openshift.io/worker: ""
      name: worker
      resourceVersion: "73802"
      uid: 0f0b3534-8b62-4ef8-9591-33e05487d9d3
    spec:
      configuration:
        name: rendered-master-9774a6215d3b1e57660c513ce0b5a630
        source:
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 00-worker
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 01-worker-container-runtime
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 01-worker-kubelet
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 97-worker-generated-kubelet
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 98-worker-generated-kubelet
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 99-worker-generated-registries
          - apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfig
            name: 99-worker-ssh
      machineConfigSelector:
        matchLabels:
          machineconfiguration.openshift.io/role: worker
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/worker: ""
      paused: false
    status:
      conditions:
        - lastTransitionTime: "2024-02-01T15:18:52Z"
          message: ""
          reason: ""
          status: "False"
          type: RenderDegraded
        - lastTransitionTime: "2024-02-01T15:57:52Z"
          message: ""
          reason: ""
          status: "False"
          type: Updated
        - lastTransitionTime: "2024-02-01T15:57:52Z"
          message: All nodes are updating to MachineConfig rendered-master-9774a6215d3b1e57660c513ce0b5a630
          reason: ""
          status: "True"
          type: Updating
        - lastTransitionTime: "2024-02-01T17:04:28Z"
          message: 'Node ip-10-0-80-190.us-west-1.compute.internal is reporting: "failed to drain node: ip-10-0-80-190.us-west-1.compute.internal after 1 hour. Please see machine-config-controller logs for more information"'
          reason: 1 nodes are reporting degraded status on sync
          status: "True"
          type: NodeDegraded
        - lastTransitionTime: "2024-02-01T17:04:28Z"
          message: ""
          reason: ""
          status: "True"
          type: Degraded
      configuration:
        name: rendered-master-9774a6215d3b1e57660c513ce0b5a630
      degradedMachineCount: 1
      machineCount: 3
      observedGeneration: 5
      readyMachineCount: 2
      unavailableMachineCount: 1
      updatedMachineCount: 2
kind: List
metadata:
  resourceVersion: ""
